version: '3.8'

services:
  db:
    image: mariadb:10.11
    ports:
      - 3345:3306
    env_file: .env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - backend
    restart: always

networks:
  backend: