name: DockerHub Latest Tag Check

on:
  workflow_dispatch:  # 수동 실행 가능하게

jobs:
  check-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest DockerHub tag for dockerhub
        run: |
          echo "Fetching latest tag for dockerhub..."
          # response=$(curl -s "https://hub.docker.com/v2/repositories/library/nginx/tags?page_size=1&page=1")
          response=$(curl -s "https://hub.docker.com/v2/repositories/neosoftbank1/webworkning_front/tags?page_size=100" \
          | jq -r '.results[].name' \
          | grep -E '^[0-9]{8}-[0-9]{2}$' \
          | sort \
          | tail -n 1 )
          echo "Latest semver tag: $response"
          latest_tag=$(echo $response | jq -r '.results[0].name')
          echo "✅ Latest dockerhub tag: $latest_tag"
